backoffice/config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.static import serve
from material.frontend.urls import modules as viewflow_apps

from web.core.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    # The govuk-frontend stylesheet requires a specific assets location
    # eg. node_modules/govuk-frontend/govuk/helpers/_font-faces.scss
    path(
        "assets/<path:asset_path>",
        RedirectView.as_view(url='/static/govuk/assets/%(asset_path)s'),
    ),
    path('auth/', include('authbroker_client.urls')),

    # Viewflow urls (includes the django /admin site)
    path('', include(viewflow_apps.urls)),

    # API
    path('api/', include('web.core.api_urls')),
    path('api/', include('web.companies.api_urls')),
    path('api/', include('web.grant_applications.api_urls')),
    path('api/', include('web.sectors.api_urls')),
    path('api/', include('web.trade_events.api_urls')),
    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url('^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

backoffice/web/grant_applications/models.py
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.db import models
from django.db.models import PROTECT
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

from web.core.abstract_models import BaseMetaModel
from web.grant_management.flows import GrantManagementFlow
from web.grant_management.models import GrantManagementProcess


class GrantApplication(BaseMetaModel):

    class NumberOfEmployees(models.TextChoices):
        HAS_FEWER_THAN_10 = 'fewer-than-10', _('Fewer than 10')
        HAS_10_TO_49 = '10-to-49', _('10 to 49')
        HAS_50_TO_249 = '50-to-249', _('50 to 249')
        HAS_250_OR_MORE = '250-or-more', _('250 or More')

        @classmethod
        def get_choice_by_number(cls, number_of_employees):
            if number_of_employees < 10:
                return cls.HAS_FEWER_THAN_10
            elif 10 <= number_of_employees <= 49:
                return cls.HAS_10_TO_49
            elif 50 <= number_of_employees <= 249:
                return cls.HAS_50_TO_249
            elif number_of_employees >= 250:
                return cls.HAS_250_OR_MORE

    class ExportRegions(models.TextChoices):
        AFRICA = 'africa', 'Africa'
        ASIA_PACIFIC = 'asia pacific', 'Asia-Pacific'
        CHINA = 'china', 'China'
        EASTERN_EUROPE_AND_CENTRAL_ASIA = \
            'eastern europe and central asia', 'Eastern Europe and Central Asia'
        EUROPE = 'europe', 'Europe'
        LATIN_AMERICA = 'latin america', 'Latin America'
        MIDDLE_EAST = 'middle east', 'Middle East'
        NORTH_AMERICA = 'north america', 'North America'
        SOUTH_ASIA = 'south asia', 'South Asia'

    class MarketsIntendingOnExportingTo(models.TextChoices):
        Existing = 'existing', 'existing markets'
        New = 'new', 'new markets not exported to in the last 12 months'

    class CompanyType(models.TextChoices):
        LIMITED_COMPANY = 'limited company', _('Limited company')
        PARTNERSHIP = 'partnership', _('Partnership')
        SOLE_TRADER = 'sole trader', _('Sole trader')
        OTHER = 'other', _('Other e.g. charity, university, publicly funded body')

    class TimeTradingInUk(models.TextChoices):
        LESS_THAN_1_YEAR = 'less than 1 year', _('Less than 1 year')
        TWO_TO_FIVE_YEARS = '2 to 5 years', _('2 to 5 years')
        SIX_TO_TEN_YEARS = '6 to 10 years', _('6 to 10 years')
        MORE_THAN_10_YEARS = 'more than 10 years', _('More than 10 years')

    previous_applications = models.IntegerField(
        null=True, validators=[MinValueValidator(0), MaxValueValidator(6)]
    )
    event = models.ForeignKey('trade_events.Event', on_delete=PROTECT, null=True)
    event_evidence_upload = models.ForeignKey('core.Image', on_delete=PROTECT, null=True)
    is_already_committed_to_event = models.BooleanField(null=True)
    search_term = models.CharField(max_length=500, null=True)
    company = models.ForeignKey('companies.Company', on_delete=PROTECT, null=True)
    manual_company_type = models.CharField(null=True, choices=CompanyType.choices, max_length=20)
    manual_company_name = models.CharField(null=True, max_length=500)
    manual_company_address_line_1 = models.CharField(null=True, max_length=100)
    manual_company_address_line_2 = models.CharField(null=True, max_length=100)
    manual_company_address_town = models.CharField(null=True, max_length=100)
    manual_company_address_county = models.CharField(null=True, max_length=100)
    manual_company_address_postcode = models.CharField(null=True, max_length=10)
    manual_time_trading_in_uk = models.CharField(
        null=True, choices=TimeTradingInUk.choices, max_length=20
    )
    manual_registration_number = models.CharField(
        null=True, validators=[RegexValidator(regex=r'(SC|NI|[0-9]{2})[0-9]{6}')], max_length=10
    )
    manual_vat_number = models.CharField(
        null=True, max_length=10,
        validators=[RegexValidator(regex=r'([0-9]{9}([0-9]{3})?|[A-Z]{2}[0-9]{3})')]
    )
    manual_website = models.URLField(null=True, max_length=500)
    number_of_employees = models.CharField(
        null=True, choices=NumberOfEmployees.choices, max_length=20
    )
    is_turnover_greater_than = models.BooleanField(null=True)
    applicant_full_name = models.CharField(null=True, max_length=500)
    applicant_email = models.EmailField(null=True)
    applicant_mobile_number = PhoneNumberField(null=True, region='GB')
    job_title = models.CharField(null=True, max_length=500)
    previous_years_turnover_1 = models.DecimalField(
        null=True, validators=[MinValueValidator(0)], **settings.CURRENCY_DECIMAL_PRECISION
    )
    previous_years_turnover_2 = models.DecimalField(
        null=True, validators=[MinValueValidator(0)], **settings.CURRENCY_DECIMAL_PRECISION
    )
    previous_years_turnover_3 = models.DecimalField(
        null=True, validators=[MinValueValidator(0)], **settings.CURRENCY_DECIMAL_PRECISION
    )
    previous_years_export_turnover_1 = models.DecimalField(
        null=True, validators=[MinValueValidator(0)], **settings.CURRENCY_DECIMAL_PRECISION
    )
    previous_years_export_turnover_2 = models.DecimalField(
        null=True, validators=[MinValueValidator(0)], **settings.CURRENCY_DECIMAL_PRECISION
    )
    previous_years_export_turnover_3 = models.DecimalField(
        null=True, validators=[MinValueValidator(0)], **settings.CURRENCY_DECIMAL_PRECISION
    )
    sector = models.ForeignKey('sectors.Sector', on_delete=PROTECT, null=True)
    other_business_names = models.CharField(null=True, max_length=500)
    products_and_services_description = models.TextField(null=True)
    products_and_services_competitors = models.TextField(null=True)
    has_exported_before = models.BooleanField(null=True)
    has_product_or_service_for_export = models.BooleanField(null=True)
    has_exported_in_last_12_months = models.BooleanField(null=True)
    export_regions = ArrayField(
        models.CharField(max_length=50, choices=ExportRegions.choices), null=True
    )
    markets_intending_on_exporting_to = ArrayField(
        models.CharField(max_length=10, choices=MarketsIntendingOnExportingTo.choices), null=True
    )
    is_in_contact_with_dit_trade_advisor = models.BooleanField(null=True)
    ita_name = models.CharField(null=True, max_length=500)
    ita_email = models.EmailField(null=True)
    ita_mobile_number = PhoneNumberField(null=True, region='GB')
    export_experience_description = models.TextField(null=True)
    export_strategy = models.TextField(null=True)
    interest_in_event_description = models.TextField(null=True)
    is_event_evidence_requested = models.BooleanField(default=False)
    is_event_evidence_uploaded = models.BooleanField(default=False)
    is_event_evidence_approved = models.BooleanField(default=False)
    is_in_contact_with_tcp = models.BooleanField(null=True)
    tcp_name = models.CharField(null=True, max_length=500)
    tcp_email = models.EmailField(null=True)
    tcp_mobile_number = PhoneNumberField(null=True, region='GB')
    is_intending_to_exhibit_as_tcp_stand = models.BooleanField(null=True)
    stand_trade_name = models.CharField(null=True, max_length=500)
    trade_show_experience_description = models.TextField(null=True)
    additional_guidance = models.TextField(null=True)
    application_summary = models.JSONField(default=list)

    def send_for_review(self):
        qs = GrantManagementFlow.process_class.objects.filter(grant_application=self)
        if not qs.exists():
            return GrantManagementFlow.start.run(grant_application=self)
        return qs.get()

    @property
    def is_eligible(self):
        if self.previous_applications and self.previous_applications >= 6:
            return False
        if self.is_already_committed_to_event is True:
            return False
        if self.number_of_employees == self.NumberOfEmployees.HAS_250_OR_MORE:
            return False
        if self.is_turnover_greater_than is True:
            return False
        return True

    @property
    def sent_for_review(self):
        return hasattr(self, 'grant_management_process')

    @property
    def is_completed(self):
        grant_management_process = getattr(self, 'grant_management_process', None)
        if grant_management_process and grant_management_process.decision:
            return True
        return False

    @property
    def company_name(self):
        return self.manual_company_name or self.company.name

    @property
    def flow_process(self):
        return GrantManagementProcess.objects.get(grant_application_id=self.id)


class StateAid(BaseMetaModel):
    authority = models.CharField(max_length=500)
    date_received = models.DateField()
    amount = models.IntegerField(validators=[MinValueValidator(1)])
    description = models.CharField(max_length=2000)
    grant_application = models.ForeignKey(GrantApplication, on_delete=PROTECT)

backoffice/web/grant_management/forms.py
from django import forms
from django.conf import settings
from material import Layout, Row, Column, Span4

from web.grant_management.models import GrantManagementProcess

VERIFY_CHOICES = ((True, 'Accept'), (False, 'Reject'))
VERIFY_LABEL = 'Do you accept or reject the applicant’s answer?'
SCORE_LABEL = 'How would you assess the applicant’s response?'
RATIONALE_LABEL = 'Rationale'
RATIONALE_PLACEHOLDER = 'Enter your rationale here'


def str_to_bool(value):
    if str(value).lower() in ['true', 't', '1']:
        return True
    elif str(value).lower() in ['false', 'f', '0']:
        return False
    raise ValueError(f'Cannot convert {value} to boolean')


class VerifyPreviousApplicationsForm(forms.ModelForm):
    class Meta:
        model = GrantManagementProcess
        fields = ['previous_applications_is_verified']

    previous_applications_is_verified = forms.TypedChoiceField(
        label=VERIFY_LABEL,
        coerce=str_to_bool,
        choices=VERIFY_CHOICES,
        widget=forms.RadioSelect
    )


class VerifyEventCommitmentForm(forms.ModelForm):
    class Meta:
        model = GrantManagementProcess
        fields = ['event_commitment_is_verified']

    event_commitment_is_verified = forms.TypedChoiceField(
        label=VERIFY_LABEL,
        coerce=str_to_bool,
        choices=VERIFY_CHOICES,
        widget=forms.RadioSelect
    )


class VerifyBusinessEntityForm(forms.ModelForm):
    class Meta:
        model = GrantManagementProcess
        fields = ['business_entity_is_verified']

    business_entity_is_verified = forms.TypedChoiceField(
        label=VERIFY_LABEL,
        coerce=str_to_bool,
        choices=VERIFY_CHOICES,
        widget=forms.RadioSelect
    )


class VerifyStateAidForm(forms.ModelForm):
    class Meta:
        model = GrantManagementProcess
        fields = ['state_aid_is_verified']

    state_aid_is_verified = forms.TypedChoiceField(
        label=VERIFY_LABEL,
        coerce=str_to_bool,
        choices=VERIFY_CHOICES,
        widget=forms.RadioSelect
    )


class EventBookingDocumentRenewForm(forms.ModelForm):

    class Meta:
        model = GrantManagementProcess
        fields = ['event_booking_document_renew_decision']

    event_booking_document_renew_decision = forms.CharField(
        widget=forms.RadioSelect(choices=GrantManagementProcess.Decision.choices)
    )


class ProductsAndServicesForm(forms.ModelForm):
    layout = Layout(
        Row('products_and_services_score'),
        Row(Span4('products_and_services_justification'), Column())
    )

    class Meta:
        model = GrantManagementProcess
        fields = ['products_and_services_score', 'products_and_services_justification']

    products_and_services_score = forms.IntegerField(
        label=SCORE_LABEL,
        widget=forms.RadioSelect(choices=GrantManagementProcess.ScoreChoices.choices)
    )
    products_and_services_justification = forms.CharField(
        label=RATIONALE_LABEL,
        widget=forms.Textarea(
            attrs={'placeholder': RATIONALE_PLACEHOLDER}
        )
    )


class ProductsAndServicesCompetitorsForm(forms.ModelForm):
    layout = Layout(
        Row('products_and_services_competitors_score'),
        Row(Span4('products_and_services_competitors_justification'), Column())
    )

    class Meta:
        model = GrantManagementProcess
        fields = [
            'products_and_services_competitors_score',
            'products_and_services_competitors_justification'
        ]

    products_and_services_competitors_score = forms.IntegerField(
        label='Score',
        widget=forms.RadioSelect(choices=GrantManagementProcess.ScoreChoices.choices)
    )
    products_and_services_competitors_justification = forms.CharField(
        label=RATIONALE_LABEL,
        widget=forms.Textarea(
            attrs={'placeholder': RATIONALE_PLACEHOLDER}
        )
    )


class ExportStrategyForm(forms.ModelForm):
    layout = Layout(
        Row('export_strategy_score'),
        Row(Span4('export_strategy_justification'), Column())
    )

    class Meta:
        model = GrantManagementProcess
        fields = ['export_strategy_score', 'export_strategy_justification']

    export_strategy_score = forms.IntegerField(
        label='Score',
        widget=forms.RadioSelect(choices=GrantManagementProcess.ScoreChoices.choices)
    )
    export_strategy_justification = forms.CharField(
        label=RATIONALE_LABEL,
        widget=forms.Textarea(
            attrs={'placeholder': RATIONALE_PLACEHOLDER}
        )
    )


class EventIsAppropriateForm(forms.ModelForm):
    class Meta:
        model = GrantManagementProcess
        fields = ['event_is_appropriate']

    event_is_appropriate = forms.TypedChoiceField(
        label='Is the trade show appropriate?',
        widget=forms.RadioSelect,
        coerce=str_to_bool,
        choices=settings.BOOLEAN_CHOICES
    )


class DecisionForm(forms.ModelForm):
    class Meta:
        model = GrantManagementProcess
        fields = ['decision']

    decision = forms.CharField(
        widget=forms.RadioSelect(choices=GrantManagementProcess.Decision.choices)
    )

backoffice/web/grant_management/views.py
from viewflow.flow.views import UpdateProcessView

from web.grant_management.mixins import SupportingInformationMixin


class BaseGrantManagementView(SupportingInformationMixin, UpdateProcessView):
    extra_context = {
        'information_card_title': 'Applicant response',
        'form_heading': 'Your assessment',
    }

backoffice/web/grant_management/templates/grant_management/grantmanagement/decision.html
{% extends "viewflow/flow/task.html" %}
{% load i18n %}

{% block information_cards %}
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ information_card_title }}</span>

    {% include "viewflow/table.html" with headers=supporting_information.table.headers rows=supporting_information.table.rows  %}

  </div>
</div>
{% endblock %}

backoffice/web/grant_management/templates/grant_management/grantmanagement/event_is_appropriate.html
{% extends "viewflow/flow/task.html" %}
{% load i18n %}

{% block information_cards %}
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ information_card_title }}</span>

    {% include "grant_management/grantmanagement/information_card_section.html" with outer_p="Why are you particularly interested in "|add:activation.process.grant_application.event.name|add:"?" inner_p=activation.process.grant_application.interest_in_event_description %}

  </div>
</div>

<div class="card">
  <div class="card-content">
    <span class="card-title">Supporting information</span>
    <p>Details provided by applicant</p>

    <strong>
      <div class="row">
        <div class="col">Event</div>
        <div class="col">
          {{ activation.process.grant_application.event.name }}<br>
          {{ activation.process.grant_application.event.sub_sector }}, {{ activation.process.grant_application.event.sector }}<br>
          {{ activation.process.grant_application.event.city }}, {{ activation.process.grant_application.event.country }}<br>
          {{ activation.process.grant_application.event.start_date }} to {{ activation.process.grant_application.event.end_date }}<br>
        </div>
      </div>

      <div class="row">
        <div class="col">Industry sector</div>
        <div class="col">
          {{ activation.process.grant_application.sector.cluster_name }}<br>
          {{ activation.process.grant_application.sector.name }}<br>
          {{ activation.process.grant_application.sector.sub_sector_name }}<br>
          {{ activation.process.grant_application.sector.sub_sub_sector_name }}<br>
        </div>
      </div>

    </strong>

  </div>
</div>
{% endblock %}

backoffice/web/grant_management/templates/grant_management/grantmanagement/export_strategy.html
{% extends "viewflow/flow/task.html" %}
{% load i18n %}

{% block information_cards %}
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ information_card_title }}</span>

    {% include "grant_management/grantmanagement/information_card_section.html" with outer_p="Provide a brief summary of your export strategy" inner_p=activation.process.grant_application.export_strategy %}

  </div>
</div>
{% endblock %}

backoffice/web/grant_management/templates/grant_management/grantmanagement/information_card_section.html
<div class="section">
  <div class="row">
    <p>{{ outer_p }}</p>
  </div>

  <div class="row">
    <div class="col s12">
      <p><strong>{{ inner_p }}</strong></p>
    </div>
  </div>

  {% if highlighted_p %}
  <div class="row grey lighten-4">
    <div class="col s12">
      <div class="section">
        <p>{{ highlighted_p }}</p>
      </div>
    </div>
  </div>
  {% endif %}

</div>

backoffice/web/grant_management/templates/grant_management/grantmanagement/products_and_services.html
{% extends "viewflow/flow/task.html" %}
{% load i18n %}

{% block information_cards %}
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ information_card_title }}</span>

    {% include "grant_management/grantmanagement/information_card_section.html" with outer_p="Describe your main products and services" inner_p=activation.process.grant_application.products_and_services_description %}

  </div>
</div>
{% endblock %}

backoffice/web/grant_management/templates/grant_management/grantmanagement/products_and_services_competitors.html
{% extends "viewflow/flow/task.html" %}
{% load i18n %}

{% block information_cards %}
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ information_card_title }}</span>

    {% include "grant_management/grantmanagement/information_card_section.html" with outer_p="Describe any advantages your products and services offer over competitors in overseas markets" inner_p=activation.process.grant_application.products_and_services_competitors %}

  </div>
</div>
{% endblock %}

backoffice/web/grant_management/templates/grant_management/grantmanagement/renew_proof_of_event_booking.html
{% extends "viewflow/flow/task.html" %}
{% load i18n %}

{% block information_cards %}
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ information_card_title }}</span>
    <div class="row">
      <a href="{{ activation.process.grant_application.event_evidence_upload.file.url }}" target="_blank">
        <img src="{{ activation.process.grant_application.event_evidence_upload.file.url }}" class="card-image content">
      </a>
      <p class="govuk-!-margin-4">Application submitted: <strong>{{ activation.process.grant_application.created }}</strong></p>
    </div>
  </div>
</div>
{% endblock %}

backoffice/web/grant_management/templates/grant_management/grantmanagement/request_event_booking_evidence.html
{% extends "viewflow/flow/task.html" %}
{% load i18n viewflow material_frontend %}


{% block information_cards %}
<div class="card">
  <div class="card-content">
    <div class="row">
      <p>The applicant has passed the initial eligibility checks and must now provide proof of their event booking</p>
    </div>
  </div>
</div>
{% endblock %}


{% block task_actions %}
<div class="col s4">
  <a class="btn btn-flat" href="{% flowurl activation.task 'detail' %}?{{ request|query_back }}">{% trans 'View task detail' %}</a>
</div>
<div class="col s8 right-align">
  <button type="submit" name="_done" class="btn primary green darken-4 white-text">{% trans 'request event booking document' %}</button>
</div>
{% endblock %}

backoffice/web/grant_management/templates/grant_management/grantmanagement/verify_business_entity.html
{% extends "viewflow/flow/task.html" %}
{% load i18n %}

{% block information_cards %}
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ information_card_title }}</span>

    {% include "grant_management/grantmanagement/information_card_section.html" with outer_p="How many employees are currently on your payroll across all UK sites?" inner_p=activation.process.grant_application.get_number_of_employees_display highlighted_p="A business must have less than 250 employees on their UK payroll to be eligible" %}
    {% include "grant_management/grantmanagement/information_card_section.html" with outer_p="Was your turnover greater than €50m, or your balance sheet (or Statement of Financial Position) greater than €43m, in the last fiscal year?" inner_p=activation.process.grant_application.is_turnover_greater_than|yesno:"Yes,No" highlighted_p="A business must have less than 250 employees on their UK payroll to be eligible" %}

    </div>
</div>

<div class="card">
  <div class="card-content">
    <span class="card-title">Supporting information</span>

    <div class="row">
      <p>Dun & Bradstreet records for {{ activation.process.grant_application.company_name }}</p>
    </div>
    <strong>
      <div class="row">
        <div class="col">Estimated employees</div>
        <div class="col">{{ supporting_information.employee_number }}</div>
      </div>
      <div class="row">
        <div class="col">Turnover</div>
        <div class="col">{{ supporting_information.annual_sales }} {{ supporting_information.annual_sales_currency }}</div>
      </div>
    </strong>

    <div class="row">
      <p>Details provided by applicant</p>
    </div>
    <strong>
      <div class="row">
        <div class="col">Turnover last year</div>
        <div class="col">{{ activation.process.grant_application.previous_years_turnover_1 }}</div>
      </div>
    </strong>

  </div>
</div>
{% endblock %}

backoffice/web/grant_management/templates/grant_management/grantmanagement/verify_event_commitment.html
{% extends "viewflow/flow/task.html" %}
{% load i18n %}

{% block information_cards %}
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ information_card_title }}</span>

    {% include "grant_management/grantmanagement/information_card_section.html" with outer_p="Have you already committed to purchasing exhibition space for "|add:activation.process.grant_application.event.name|add:"?" inner_p=activation.process.grant_application.is_already_committed_to_event|yesno:"Yes,No" highlighted_p="A business cannot have committed to an event before applying for a TAP grant" %}

  </div>
</div>
{% endblock %}

backoffice/web/grant_management/templates/grant_management/grantmanagement/verify_previous_applications.html
{% extends "viewflow/flow/task.html" %}
{% load i18n %}

{% block information_cards %}
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ information_card_title }}</span>

    {% include "grant_management/grantmanagement/information_card_section.html" with outer_p="How many grants have you received from TAP since April 1st 2009?" inner_p=activation.process.grant_application.previous_applications highlighted_p="A business is allowed up to 6 TAP grants in total" %}

  </div>
</div>
{% endblock %}

backoffice/web/grant_management/templates/grant_management/grantmanagement/verify_state_aid.html
{% extends "viewflow/flow/task.html" %}
{% load i18n %}

{% block information_cards %}
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ information_card_title }}</span>

    {% include "viewflow/table.html" with headers=supporting_information.table.headers rows=supporting_information.table.rows  %}

  </div>
</div>
{% endblock %}