frontend/config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

handler404 = 'web.core.views.handler404'
handler500 = 'web.core.views.handler500'

urlpatterns = [
    # The govuk-frontend stylesheet requires a specific assets location
    # eg. node_modules/govuk-frontend/govuk/helpers/_font-faces.scss
    path(
        'assets/<path:asset_path>',
        RedirectView.as_view(url='/static/govuk-frontend/govuk/assets/%(asset_path)s'),
    ),
    path(
        'hmcts-assets/<path:asset_path>',
        RedirectView.as_view(url='/static/@hmcts/frontend/assets/%(asset_path)s'),
    ),

    # Templates
    path('', RedirectView.as_view(url='grant-applications/')),
    path('users/', include('web.users.urls', namespace='users')),
    path('grant-applications/', include('web.grant_applications.urls', namespace='grant-applications')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url('^__debug__/', include(debug_toolbar.urls)),
        path('admin/', admin.site.urls),
    ] + urlpatterns

frontend/web/grant_applications/urls.py
from django.urls import path
from django.views.generic import TemplateView

from web.grant_applications.views import (
    SearchCompanyView, SelectCompanyView, ContactDetailsView, SelectAnEventView,
    PreviousApplicationsView, CompanyTradingDetailsView, ExportExperienceView, StateAidSummaryView,
    ApplicationReviewView, FindAnEventView, BeforeYouStartView, EventCommitmentView,
    CompanyDetailsView, ExportDetailsView, TradeEventDetailsView, AddStateAidView, EditStateAidView,
    DeleteStateAidView, DuplicateStateAidView, ManualCompanyDetailsView,
    StartNewApplicationView, MagicLinkHandlerView, SelectApplicationProgressView,
    CheckYourEmailView, InvalidMagicLinkView, ExpiredMagicLinkView,
    NoApplicationFoundView, ContinueApplicationView, ApplicationIndexView, EventEvidenceUploadView,
    EventEvidenceUploadCompleteView
)

app_name = 'grant_applications'

urlpatterns = [
    path('', ApplicationIndexView.as_view(), name='index'),
    path('before-you-start/', BeforeYouStartView.as_view(), name='before-you-start'),
    path(
        'new-application-email/',
        StartNewApplicationView.as_view(),
        name='new-application-email'
    ),
    path(
        'continue-application-email/',
        ContinueApplicationView.as_view(),
        name='continue-application-email'
    ),
    path(
        'select-application-progress/',
        SelectApplicationProgressView.as_view(),
        name='select-application-progress'
    ),
    path('check-your-email/', CheckYourEmailView.as_view(), name='check-your-email'),
    path('resume/<hash>/', MagicLinkHandlerView.as_view(), name='magic-link'),
    path('invalid-link/', InvalidMagicLinkView.as_view(), name='invalid-magic-link'),
    path('expired-link/', ExpiredMagicLinkView.as_view(), name='expired-magic-link'),
    path('no-application-found/', NoApplicationFoundView.as_view(), name='no-application-found'),
    path(
        '<pk>/previous-applications/',
        PreviousApplicationsView.as_view(),
        name='previous-applications'
    ),
    path('<pk>/find-an-event/', FindAnEventView.as_view(), name='find-an-event'),
    path('<pk>/select-an-event/', SelectAnEventView.as_view(), name='select-an-event'),
    path('<pk>/event-commitment/', EventCommitmentView.as_view(), name='event-commitment'),
    path('<pk>/search-company/', SearchCompanyView.as_view(), name='search-company'),
    path('<pk>/select-company/', SelectCompanyView.as_view(), name='select-company'),
    path(
        '<pk>/manual-company-details/',
        ManualCompanyDetailsView.as_view(),
        name='manual-company-details'
    ),
    path('<pk>/company-details/', CompanyDetailsView.as_view(), name='company-details'),
    path('<pk>/contact-details/', ContactDetailsView.as_view(), name='contact-details'),
    path(
        '<pk>/company-trading-details/',
        CompanyTradingDetailsView.as_view(),
        name='company-trading-details'
    ),
    path('<pk>/export-experience/', ExportExperienceView.as_view(), name='export-experience'),
    path('<pk>/export-details/', ExportDetailsView.as_view(), name='export-details'),
    path('<pk>/trade-event-details/', TradeEventDetailsView.as_view(), name='trade-event-details'),
    path('<pk>/state-aid-summary/', StateAidSummaryView.as_view(), name='state-aid-summary'),
    path('<pk>/add-state-aid/', AddStateAidView.as_view(), name='add-state-aid'),
    path('<pk>/edit-state-aid/<state_aid_pk>/', EditStateAidView.as_view(), name='edit-state-aid'),
    path(
        '<pk>/delete-state-aid/<state_aid_pk>/',
        DeleteStateAidView.as_view(),
        name='delete-state-aid'
    ),
    path(
        '<pk>/duplicate-state-aid/<state_aid_pk>/',
        DuplicateStateAidView.as_view(),
        name='duplicate-state-aid'
    ),
    path('<pk>/application-review/', ApplicationReviewView.as_view(), name='application-review'),
    path(
        '<pk>/confirmation/',
        TemplateView.as_view(template_name='grant_applications/confirmation.html'),
        name='confirmation'
    ),
    path(
        'ineligible/',
        TemplateView.as_view(template_name='grant_applications/ineligible.html'),
        name='ineligible'
    ),

    path(
        '<pk>/event-booking-evidence-upload/',
        EventEvidenceUploadView.as_view(),
        name='event-evidence-upload'
    ),
    path(
        '<pk>/event-booking-evidence-complete/',
        EventEvidenceUploadCompleteView.as_view(),
        name='event-evidence-upload-complete'
    )
]

frontend/web/grant_applications/models.py
from uuid import uuid4

from django.db import models
from django.urls import reverse, NoReverseMatch


class GrantApplicationLink(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    backoffice_grant_application_id = models.UUIDField(unique=True)
    has_viewed_review_page = models.BooleanField(default=False)
    email = models.EmailField()
    state_url_name = models.CharField(max_length=255, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(editable=False, auto_now_add=True)

    APPLICATION_FIRST_STEP_URL_NAME = 'grant_applications:previous-applications'

    @property
    def state_url(self):
        first_step_url = reverse(self.APPLICATION_FIRST_STEP_URL_NAME, args=(self.id,))
        if self.state_url_name:
            try:
                return reverse(self.state_url_name, args=(self.id, ))
            except NoReverseMatch:
                return first_step_url
        return first_step_url

frontend/web/grant_applications/views.py
from django import forms
from django.core.signing import SignatureExpired, BadSignature
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse, resolve
from django.utils import timezone
from django.utils.http import urlencode
from django.utils.translation import gettext_lazy as _
from django.views.generic import UpdateView, RedirectView, TemplateView, FormView
from django.views.generic.detail import SingleObjectMixin, DetailView

from web.core.forms import FORM_MSGS
from web.core.view_mixins import (
    SuccessUrlObjectPkMixin, BackContextMixin, PaginationMixin, SaveStateMixin
)
from web.grant_applications.constants import APPLICATION_BACKOFFICE_ID_SESSION_KEY
from web.grant_applications.forms import (
    SearchCompanyForm, SelectCompanyForm, SelectAnEventForm, PreviousApplicationsForm,
    CompanyTradingDetailsForm, ExportExperienceForm, FindAnEventForm,
    EmptyGrantApplicationLinkForm, EventCommitmentForm, CompanyDetailsForm, ContactDetailsForm,
    ExportDetailsForm, TradeEventDetailsForm, AddStateAidForm, EditStateAidForm,
    ManualCompanyDetailsForm, ApplicationEmailForm, ApplicationProgressForm,
    EventEvidenceUploadForm
)
from web.grant_applications.models import GrantApplicationLink
from web.grant_applications.services import (
    BackofficeServiceException, BackofficeService, get_companies_from_search_term,
    get_state_aid_summary_table, ApplicationReviewService
)
from web.grant_applications.utils import (
    send_resume_application_email, decrypting_data, get_active_backoffice_application,
    RESUME_APPLICATION_ACTION, UPLOAD_EVENT_BOOKING_EVIDENCE_ACTION
)

from web.grant_applications.view_mixins import (
    BackofficeMixin, InitialDataMixin, ConfirmationRedirectMixin, IneligibleRedirectMixin
)


class ApplicationIndexView(TemplateView):
    template_name = 'grant_applications/index.html'

    def clean_session_data(self):
        self.request.session.pop(APPLICATION_BACKOFFICE_ID_SESSION_KEY, None)

    def get(self, request, *args, **kwargs):
        self.clean_session_data()
        return super().get(request, *args, **kwargs)


class MagicLinkHandlerView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        invalid_link_url = reverse('grant_applications:invalid-magic-link')
        expired_link_url = reverse('grant_applications:expired-magic-link')
        hash_value = self.kwargs.get('hash')
        if not hash_value:
            return invalid_link_url

        try:
            data = decrypting_data(hash_value)
        except SignatureExpired:
            return expired_link_url
        except BadSignature:
            return invalid_link_url

        if data.get('action-type') == RESUME_APPLICATION_ACTION:
            return data.get('redirect-url', invalid_link_url)

        if data.get('action-type') == UPLOAD_EVENT_BOOKING_EVIDENCE_ACTION:
            application_backoffice_id = data.get('application-backoffice-id')
            try:
                grant_application_link = GrantApplicationLink.objects.get(
                    backoffice_grant_application_id=application_backoffice_id
                )
                return reverse(
                    'grant_applications:event-evidence-upload',
                    args=(grant_application_link.id,)
                )
            except GrantApplicationLink.DoesNotExist:
                pass

        return invalid_link_url


class InvalidMagicLinkView(FormView):
    template_name = 'grant_applications/invalid-magic-link.html'
    form_class = ApplicationEmailForm
    success_url_name = 'grant_applications:check-your-email'
    extra_context = {
        'page': {
            'heading': _('The link is invalid'),
            'heading_text': _(
                'That sign in link is not valid. To continue your application, '
                'enter your email address and we’ll send you a new secure link.'
            )
        },
        'button_text': 'Continue'
    }

    @property
    def user_application_backoffice_id(self):
        return self.request.session.get(APPLICATION_BACKOFFICE_ID_SESSION_KEY)

    def set_application_reference_session(self, backoffice_id):
        self.request.session[APPLICATION_BACKOFFICE_ID_SESSION_KEY] = backoffice_id

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        backoffice_application = get_active_backoffice_application(email=email)
        if backoffice_application:
            self.request.session[APPLICATION_BACKOFFICE_ID_SESSION_KEY] = backoffice_application['id']
            try:
                grant_application_link = GrantApplicationLink.objects.get(
                    backoffice_grant_application_id=backoffice_application['id']
                )
                send_resume_application_email(grant_application_link)
                self.set_application_reference_session(
                    str(grant_application_link.backoffice_grant_application_id)
                )
                return HttpResponseRedirect(reverse(self.success_url_name))
            except GrantApplicationLink.DoesNotExist:
                pass
        return HttpResponseRedirect(reverse('grant_applications:no-application-found'))


class ExpiredMagicLinkView(InvalidMagicLinkView):
    template_name = 'grant_applications/expired-magic-link.html'
    extra_context = {
        'page': {
            'heading': _('The link has expired'),
            'heading_text': _(
                'That sign in link has expired. To continue your application, '
                'enter your email address and we’ll send you a new secure link.'
            )
        },
        'button_text': 'Continue'
    }


class NoApplicationFoundView(InvalidMagicLinkView):
    template_name = 'grant_applications/no-application-found.html'
    extra_context = {
        'page': {
            'heading': _('No application found'),
        },
        'button_text': 'Continue'
    }


class CheckYourEmailView(BackContextMixin, TemplateView):
    template_name = 'grant_applications/check-your-email.html'
    back_url_name = 'grant-applications:before-you-start'
    extra_context = {
        'page': {
            'heading': _('Confirm your email address')
        }
    }

    def get_back_url(self):
        if self.linked_application:
            return reverse('grant-applications:continue-application-email')
        return reverse('grant-applications:new-application-email')

    @property
    def linked_application(self):
        try:
            return GrantApplicationLink.objects.get(
                backoffice_grant_application_id=self.user_application_backoffice_id
            )
        except GrantApplicationLink.DoesNotExist:
            pass

        return None

    @property
    def user_application_backoffice_id(self):
        return self.request.session.get(APPLICATION_BACKOFFICE_ID_SESSION_KEY)

    def get(self, request, *args, **kwargs):
        if not self.user_application_backoffice_id:
            return HttpResponseRedirect(reverse('grant_applications:index'))
        return super().get(request, *args, **kwargs)


class BeforeYouStartView(BackContextMixin, TemplateView):
    template_name = 'grant_applications/before_you_start.html'
    back_url_name = 'grant-applications:index'
    success_url_name = 'grant_applications:new-application-email'
    extra_context = {
        'page': {
            'heading': _('What you will need')
        }
    }


class StartNewApplicationView(BackContextMixin, SuccessUrlObjectPkMixin, FormView):
    model = GrantApplicationLink
    form_class = ApplicationEmailForm
    template_name = 'grant_applications/application-email.html'
    back_url_name = 'grant-applications:before-you-start'
    success_url_name = 'grant-applications:check-your-email'
    extra_context = {
        'page': {
            'heading': _('Register your email'),
            'heading_text': _(
                'Before you start, register your business email address '
                'and we will send you a secure sign in link. You will also '
                'be able to use your email address to return to your application.'
            )
        },
        'button_text': 'Continue'
    }

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        self.request.session.pop(APPLICATION_BACKOFFICE_ID_SESSION_KEY, None)
        backoffice_application = get_active_backoffice_application(email=email)
        if backoffice_application:
            self.request.session[APPLICATION_BACKOFFICE_ID_SESSION_KEY] = backoffice_application['id']
            return HttpResponseRedirect(
               reverse('grant_applications:select-application-progress')
            )

        try:
            backoffice_grant_application = BackofficeService().create_grant_application()
            self.request.session[APPLICATION_BACKOFFICE_ID_SESSION_KEY] = backoffice_grant_application['id']
        except BackofficeServiceException:
            form.add_error(None, forms.ValidationError(FORM_MSGS['resubmit']))
            return super().form_invalid(form)
        grant_application_link = GrantApplicationLink(
            email=email,
            backoffice_grant_application_id=backoffice_grant_application['id'],
            state_url_name=self.success_url_name
        )
        grant_application_link.save()
        send_resume_application_email(grant_application_link)
        return HttpResponseRedirect(reverse(self.success_url_name))


class ContinueApplicationView(StartNewApplicationView):
    back_url_name = 'grant-applications:index'
    extra_context = {
        'page': {
            'heading': _('Enter your email'),
            'heading_text': _(
                'To continue with your application please enter the business '
                'email address you registered with and we will send you a '
                'secure sign in link.'
            )
        },
        'button_text': 'Continue'
    }

    def form_valid(self, form):

frontend/web/grant_applications/templates/grant_applications/about_you.html
{% extends 'grant_applications/generic_form_page.html' %}

{% block headings %}
  <span class="govuk-caption-l">{{ page.caption }}</span>
  <h2 class="govuk-heading-l govuk-!-margin-bottom-4">{{ page.heading }}</h2>
  <p class="govuk-body">We’ll only use these details if we need to contact you regarding this application</p>
  <div class="govuk-!-padding-bottom-4"></div>
{% endblock %}

frontend/web/grant_applications/templates/grant_applications/application-email.html
{% extends "grant_applications/generic_form_page.html" %}

frontend/web/grant_applications/templates/grant_applications/before_you_start.html
{% extends "grant_applications/generic_form_page.html" %}

{% block forms %}
<div class="govuk-grid-row">

  <div class="govuk-grid-column-three-quarters">

    <p class="govuk-body">
      To complete the application you’ll need:
    </p>
    <ul class="govuk-list govuk-list--bullet">
      <li>details of the event you’re interested in exhibiting at</li>
      <li>details of your business and the products or services it provides</li>
      <li>the business turnover for the last 3 fiscal years</li>
    </ul>

    <p class="govuk-body">
      In addition you will also need to provide details of:
    </p>
    <ul class="govuk-list govuk-list--bullet">
      <li>any state aid received in the last 3 years</li>
      <li>your trade show experience</li>
      <li>your export experience</li>
      <li>your export strategy and export plan, if you have one</li>
      <li>any DIT trade advisors or DIT-approved trade associations (also known as Trade Challenge Partners) that you’re in contact with</li>
    </ul>

    {% include 'core/govt_uk_details.html' with summary_text='What are DIT trade advisors and TCPs?' text='The DIT offers support to businesses considering international trade through International Trade Advisors. They act as independent mentors to both those new to, and experienced in exporting. They can help with everything from preparing for trade shows, creating an export growth action plan, advising on which markets are best for your business, and putting you touch with contacts who can help your international expansion.<br><br>Trade Challenge Partners, or TCPs, are trade associations and other industry representative organisations focused on overseas trade that are accredited by the DIT. Reflecting every sector and industry in the UK, accreditation allows these DIT partners to work with us to deliver customer-focused trade shows and events.' %}

    {% url 'grant-applications:new-application-email' as application_email_href %}
    {% include "core/govt_uk_link_button.html" with text="Continue" class="govuk-button" href=application_email_href %}

  </div>

</div>
{% endblock %}

frontend/web/grant_applications/templates/grant_applications/business_details.html
{% extends 'grant_applications/generic_form_page.html' %}

frontend/web/grant_applications/templates/grant_applications/check-your-email.html
{% extends "grant_applications/generic_form_page.html" %}

{% block heading_text %}
  <p class="govuk-body govuk-!-margin-bottom-6">We’ve sent an email to <strong>{{ view.user_email }}</strong>. Click on the link to confirm your address and return to this service.</p>
  <p class="govuk-body govuk-!-margin-bottom-6">If your email doesn’t arrive within 5 minutes, check your spam <br>
    folder – or
    {% if view.linked_application %}
      <a href="{% url 'grant-applications:continue-application-email' %}">try resending the link</a>.
    {% else %}
      <a href="{% url 'grant-applications:new-application-email' %}">try resending the link</a>.
    {% endif %}
  </p>
{% endblock %}


{% block forms %}
{% endblock %}

frontend/web/grant_applications/templates/grant_applications/company_details.html
{% extends 'core/govt_uk_form_page.html' %}

frontend/web/grant_applications/templates/grant_applications/event_evidence_upload_complete.html
{% extends "core/base.html" %}

{% block content %}

<div class="govuk-width-container">
  <main class="govuk-main-wrapper govuk-main-wrapper--l" id="main-content" role="main">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <div class="govuk-panel govuk-panel--confirmation">
          <h1 class="govuk-panel__title">Event confirmation shared successfully</h1>
          <div class="govuk-panel__body">
            Your reference number<br><strong>{{ view.backoffice_grant_application.id }}</strong>
          </div>
        </div>

        <p class="govuk-body">We have sent you a confirmation email.</p>

        <h2 class="govuk-heading-m">What happens next</h2>

        <p class="govuk-body">Your proof of booking exhibition space at {{ view.backoffice_grant_application.event.name }} has been sent to the Tradeshow Access Programme team.</p>
        <p class="govuk-body">They will contact you in the next 2 to 3 weeks using the details you’ve provided to confirm whether your application has been successful or to ask you for any further information.</p>
      </div>
    </div>
  </main>
</div>

{% endblock %}

frontend/web/grant_applications/templates/grant_applications/event_finance.html
{% extends 'grant_applications/generic_form_page.html' %}

frontend/web/grant_applications/templates/grant_applications/expired-magic-link.html
{% extends "grant_applications/generic_form_page.html" %}

frontend/web/grant_applications/templates/grant_applications/ineligible.html
{% extends "core/base.html" %}

{% block content %}

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h2 class="govuk-heading-l">You are not eligible for a Tradeshow Access Programme (TAP) grant</h2>
    <p class="govuk-body">We’re sorry but based on the information you’ve provided your business is ineligible for a TAP grant at this time.</p>


    <h2 class="govuk-heading-m">Next steps</h2>
    <ul class="govuk-list govuk-list--bullet">
      <li><a class="govuk-link govuk-link--no-visited-state" href="{% url 'grant-applications:index' %}">Start a new TAP grant application</a></li>
      <li><a class="govuk-link govuk-link--no-visited-state" href="#">Contact your local DIT trade advisor for further information</a></li>
    </ul>

  </div>
</div>

{% endblock %}

frontend/web/grant_applications/templates/grant_applications/manual_company_details.html
{% extends 'core/govt_uk_form_page.html' %}

{% block govuk_form %}

<form class="form" method="POST" novalidate>
  {% csrf_token %}
  {% include "core/govt_uk_form_non_field_errors.html" with non_field_errors=form.non_field_errors %}

  {% include "core/govt_uk_form_field.html" with field=form.manual_company_type %}
  {% include "core/govt_uk_form_field.html" with field=form.manual_company_name %}

  <fieldset class="govuk-fieldset">
    <legend class="govuk-fieldset__legend govuk-fieldset__legend--s">
      <h1 class="govuk-fieldset__heading">Business address</h1>
      <div class="govuk-hint govuk-!-margin-bottom-0">Enter the UK address the business is registered at</div>
    </legend>
    {% include "core/govt_uk_form_field.html" with field=form.manual_company_address_line_1 %}
    {% include "core/govt_uk_form_field.html" with field=form.manual_company_address_line_2 %}
    {% include "core/govt_uk_form_field.html" with field=form.manual_company_address_town %}
    {% include "core/govt_uk_form_field.html" with field=form.manual_company_address_county %}
    {% include "core/govt_uk_form_field.html" with field=form.manual_company_address_postcode %}
  </fieldset>

  {% include "core/govt_uk_form_field.html" with field=form.manual_time_trading_in_uk %}
  {% include "core/govt_uk_form_field.html" with field=form.manual_registration_number %}
  {% include "core/govt_uk_form_field.html" with field=form.manual_vat_number %}
  {% include "core/govt_uk_form_field.html" with field=form.manual_website %}

  {% include "core/govt_uk_form_button.html" with button_class=button_class button_name=button_name button_text=button_text %}
</form>

{% endblock %}

frontend/web/grant_applications/templates/grant_applications/no-application-found.html
{% extends "grant_applications/generic_form_page.html" %}
{% block heading_text %}
  <p class="govuk-body govuk-!-margin-bottom-6">
    The email <strong>{{ view.user_email }}</strong> didn’t correspond to any TAP grant application.
    Try entering your email again, or <a href="{% url 'grant_applications:index' %}">start a new application</a>.
  </p>
{% endblock %}

frontend/web/grant_applications/templates/grant_applications/select_company.html
{% extends 'core/govt_uk_form_page.html' %}

{% block before_govuk_form %}

{% include "core/govt_uk_form_non_field_errors.html" with non_field_errors=form.non_field_errors %}

<div class="hmcts-search govuk-!-margin-bottom-4">
  <form class="form" id="id_search_form" method="GET" novalidate>
    {% include "core/govt_uk_form_field.html" with field=form.search_term %}
    {% include "core/govt_uk_form_button.html" with button_class='govuk-button govuk-button--secondary hmcts-search__button' button_text="Search" %}
  </form>
</div>

{% endblock %}

{% block govuk_form %}
{% if number_of_matches > 0 %}
  <p class="govuk-body govuk-!-font-weight-bold" id="id_matches_text">We found {{ number_of_matches }} match{{ number_of_matches|pluralize:"es" }}</p>

  <form class="form" method="POST" novalidate>
    {% csrf_token %}
    {% include "core/govt_uk_form_field.html" with field=form.duns_number %}
    {% include "core/govt_uk_form_button.html" with button_class=button_class button_name=button_name button_text=button_text %}
  </form>

  <span class="govuk-body">If your business isn’t listed, <a id="id_details_not_listed" href="{% url 'grant-applications:manual-company-details' pk=grantapplicationlink.pk %}" class="govuk-link govuk-link--no-visited-state">enter your details manually</a>.</span>
{% else %}
  <p class="govuk-body govuk-!-font-weight-bold" id="id_matches_text">We found no matching businesses</p>
  <p class="govuk-body">Try checking the spelling of your business name or <a id="id_details_not_listed" href="{% url 'grant-applications:manual-company-details' pk=grantapplicationlink.pk %}" class="govuk-link govuk-link--no-visited-state">enter your details manually</a>.</p>
{% endif %}

{% endblock %}

frontend/web/grant_applications/templates/grant_applications/trade_event_details.html
{% extends 'core/govt_uk_form_page.html' %}

{% block govuk_form %}
<form class="form" method="POST" novalidate>
  {% csrf_token %}
  {% include "core/govt_uk_form_non_field_errors.html" with non_field_errors=form.non_field_errors %}
  {% include "core/govt_uk_form_field.html" with field=form.interest_in_event_description %}

  <div class="govuk-form-group{% if form.is_in_contact_with_tcp.errors %} govuk-form-group--error{% endif %}">
    {% include "core/govt_uk_form_field_label.html" with field=form.is_in_contact_with_tcp %}
    {% include "core/govt_uk_form_field_hint.html" with field=form.is_in_contact_with_tcp %}
    {% include "core/govt_uk_form_field_errors.html" with field=form.is_in_contact_with_tcp %}

    <fieldset class="govuk-fieldset">

      {% include "core/govt_uk_details.html" with text=form.is_in_contact_with_tcp.field.widget.attrs.details.text summary_text=form.is_in_contact_with_tcp.field.widget.attrs.details.summary_text %}

      <div class="govuk-radios govuk-radios--conditional" data-module="govuk-radios">

        <div class="govuk-radios__item">
          {% ifequal form.is_in_contact_with_tcp.value|cut:"'" form.is_in_contact_with_tcp.subwidgets.0.data.value|cut:"'" %}
            <input class="govuk-radios__input" id="id_is_in_contact_with_tcp_01" name="is_in_contact_with_tcp" type="radio" value="True" data-aria-controls="tcp_details-conditional" checked>
          {% else %}
            <input class="govuk-radios__input" id="id_is_in_contact_with_tcp_02" name="is_in_contact_with_tcp" type="radio" value="True" data-aria-controls="tcp_details-conditional">
          {% endifequal %}
          <label class="govuk-label govuk-radios__label" for="id_is_in_contact_with_tcp_0">
            {{ form.is_in_contact_with_tcp.subwidgets.0.choice_label }}
          </label>
        </div>

        <div class="govuk-radios__conditional govuk-radios__conditional--hidden" id="tcp_details-conditional">
          <p class="govuk-body">Provide the contact details of the TCP, including at least an email address or a phone number</p>
          {% include "core/govt_uk_form_field.html" with field=form.tcp_name %}
          {% include "core/govt_uk_form_field.html" with field=form.tcp_email %}
          {% include "core/govt_uk_form_field.html" with field=form.tcp_mobile_number %}
        </div>

        <div class="govuk-radios__item">
          {% ifequal form.is_in_contact_with_tcp.value|cut:"'" form.is_in_contact_with_tcp.subwidgets.1.data.value|cut:"'" %}
            <input class="govuk-radios__input" id="id_is_in_contact_with_tcp_11" name="is_in_contact_with_tcp" type="radio" value="False" checked>
          {% else %}
            <input class="govuk-radios__input" id="id_is_in_contact_with_tcp_12" name="is_in_contact_with_tcp" type="radio" value="False">
          {% endifequal %}
          <label class="govuk-label govuk-radios__label" for="id_is_in_contact_with_tcp_1">
            {{ form.is_in_contact_with_tcp.subwidgets.1.choice_label }}
          </label>
        </div>

      </div>
    </fieldset>
  </div>

  {% include "core/govt_uk_form_field.html" with field=form.is_intending_to_exhibit_as_tcp_stand %}
  {% include "core/govt_uk_form_field.html" with field=form.stand_trade_name %}
  {% include "core/govt_uk_form_field.html" with field=form.trade_show_experience_description %}
  {% include "core/govt_uk_form_field.html" with field=form.additional_guidance %}
  {% include "core/govt_uk_form_button.html" with button_class=button_class button_name=button_name button_text=button_text %}
</form>
{% endblock %}